# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yml')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Iterate through entries in YAML file
  servers.each do |servers|
    config.ssh.forward_agent = true
    # config.vm.synced_folder Dir.pwd, "/vagrant", disabled: true
    # config.vm.synced_folder ".", "/vagrant", type: "nfs"
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
      end
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    # ansible.tags = ["jenkins_master_config"]
   end
end
